name: Release

on:
  push:
    branches: [*]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.17
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Prettier check
        run: pnpm run format:check

      - name: Lint
        run: pnpm run lint

      - name: Unit tests
        run: pnpm run test:ci

      - name: Build
        run: pnpm run build

      - name: Create Release PR or Publish
        uses: changesets/action@v1
        with:
          version: pnpm run version-packages
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}